In [ ]:

# points a, b and, c
a, b, c, d = (0, 0, 1), (0, 1, 1), (1, 1, 1), (1, 0, 1) #In homogenous form
# matrix with row vectors of points
P = np.array([a, b, c, d]).T
P = P/P[-1, :]  #divide by the last row to get inhomogeneous coordinates no use here idk why
P = np.insert(P,4,P[:,0],axis=1) 
x = P[0, :] #first row of P
y = P[1, :] #second row of P
print("Points \n", P) 
fig, ax = plt.subplots(1,1, sharex=True, sharey=True)                                                                     

#Original points                            
ax.plot(x, y, color='#6699cc', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
ax.set_aspect('equal')


#First transformation 
H_1 = np.identity(3)
H_1[0,0] = 3.5
H_1[1,1] = 3.5
H_1[2, 0] = 0
H_1[2, 1] = 0
print("H_1 \n",H_1)
Pt_1 = np.matmul(H_1, P)
Pt_1 = Pt_1/Pt_1[-1, :]  #Converting to inhomogeneous coordinates
Pt_1 = np.insert(Pt_1,4,Pt_1[:,0],axis=1) #take the first column and append to the last, so the last point is plotted twice completing the square, omfg
xt_1 = Pt_1[0, :]
yt_1 = Pt_1[1, :]
ax.plot(xt_1, yt_1, color='#ff00cc', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
ax.set_aspect('equal')


#Second transformation
t = np.pi/3
H_2 = np.array(([np.cos(t), np.sin(t), 0.], [-np.sin(t), np.cos(t), 0.], [0., 0., 1.]))
print("H_2\n",H_2)
Pt_2 = np.matmul(H_2,P) 
Pt_2 = Pt_2/Pt_2[-1, :]
Pt_2 = np.insert(Pt_2,4,Pt_2[:,0],axis=1)  
xt_2 = Pt_2[0, :]
yt_2 = Pt_2[1, :]
ax.plot(xt_2, yt_2, color='#ff0100', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
ax.set_aspect('equal')


#third transformation
#H_3 = np.array(([-1,0,0], [0,1,0], [0., 0., 1.]))
#print("H_3 \n",H_3)
#Pt_3 = np.matmul(H_3,P)
#Pt_3 = Pt_3/Pt_3[-1, :]
#Pt_3 = np.insert(Pt_3,4,Pt_3[:,0],axis=1)  
#xt_3 = Pt_3[0, :]
#yt_3 = Pt_3[1, :]
#ax.plot(xt_3, yt_3, color='#42f55a', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
#ax.set_aspect('equal')

H_3 = np.array(([1,0,0], [1,1,0], [0., 0., 1.]))
print("H_3 \n",H_3)
Pt_3 = np.matmul(H_3,P)
Pt_3 = Pt_3/Pt_3[-1, :]
Pt_3 = np.insert(Pt_3,4,Pt_3[:,0],axis=1)  
xt_3 = Pt_3[0, :]
yt_3 = Pt_3[1, :]
ax.plot(xt_3, yt_3, color='#42f55a', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
ax.set_aspect('equal')

H_4 = np.identity(3)
H_4[0,0] = 2
H_4[1,1] = 2
H_4[2, 0] = 0.3
H_4[2, 1] = 0.5
print("H_4 \n",H_4)
Pt_4 = np.matmul(H_4,P)
Pt_4 = Pt_4/Pt_4[-1, :]
Pt_4 = np.insert(Pt_4,4,Pt_4[:,0],axis=1)  
xt_4 = Pt_4[0, :]
yt_4 = Pt_4[1, :]
ax.plot(xt_4, yt_4, color='#a87f32', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
ax.set_aspect('equal')
#fourth transformation
H_5 = np.array([[1,0,5],[0,1,2],[0,0,1]])
print("H_5 \n",H_5)
Pt_5 = np.matmul(H_5,P)
Pt_5 = Pt_5/Pt_5[-1, :]
Pt_5 = np.insert(Pt_5,4,Pt_5[:,0],axis=1)  
xt_5 = Pt_5[0, :]
yt_5 = Pt_5[1, :]
ax.plot(xt_5, yt_5, color='#404505', alpha=0.7,linewidth=3, solid_capstyle='round', zorder=2)
plt.legend(['Original','1','2','3','4','5'],loc='lower right')
ax.set_aspect('equal')
plt.show()

In [ ]:
with open('images/assn2/graf/H1to5p') as f:
    H = [[float(x) for x in line.split()] for line in f]
print(H)
H = np.array(H)

canvas = np.empty((1000,1000,3),dtype='uint8')
h, w = im1.shape[0:2]
Y, X = np.indices((h,w))                                                
homo_coods = np.stack((X.ravel(), Y.ravel(), np.ones(Y.size)))
homo_coods_trans = H.dot(homo_coods)
homo_coods_trans /= homo_coods_trans[2,:]
iteration =0
for row in range(im1.shape[0]):
    for col in range(im1.shape[1]):
        v = homo_coods_trans[0][iteration]
        u = homo_coods_trans[1][iteration]
        u = int(round(u))
        v = int(round(v))
        canvas[u][v] = im1[row,col]
        iteration += 1
canvas[0:im1.shape[0], 0:im1.shape[1]] = im5
cv.imwrite('Q2.jpg',canvas)
cv.namedWindow("Image 1", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 1", im1)
cv.waitKey(0)
cv.namedWindow("Image 5", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 5", im5)
cv.waitKey(0)
cv.namedWindow("Stitched", cv.WINDOW_AUTOSIZE)
cv.imshow("Stitched", canvas)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
N = 5
global n
n = 0
p1 = np.empty((N,2))
p2 = np.empty((N,2))

# mouse callback function
def draw_circle(event,x,y,flags,param):
    global n
    p = param[0]
    if event == cv.EVENT_LBUTTONDOWN:  
        cv.circle(param[1],(x,y),5,(255,0,0),-1)
        p[n] = (x,y)
        n += 1

im1 = cv.imread('images/assn2/graf/img1.ppm', cv.IMREAD_ANYCOLOR)
im4 = cv.imread('images/assn2/graf/img4.ppm', cv.IMREAD_ANYCOLOR)

im1copy = im1.copy()
im4copy = im4.copy()

cv.namedWindow('Image 1', cv.WINDOW_AUTOSIZE)

param = [p1, im1copy]
cv.setMouseCallback('Image 1',draw_circle, param)

while(1):
    cv.imshow("Image 1", im1copy)
    if n == N:
        break
    if cv.waitKey(20) & 0xFF == 27:
        break

cv.namedWindow("Image 4", cv.WINDOW_AUTOSIZE)
param = [p2, im4copy]
n = 0
cv.setMouseCallback('Image 4',draw_circle, param)

while(1):
    cv.imshow("Image 4", im4copy)
    if n == N:
        break
    if cv.waitKey(20) & 0xFF == 27:
        break

print(p1)
print(p2)
print(H)
(H, status) = cv.findHomography(p1, p2,0)
im4_warped = cv.warpPerspective(im4, np.linalg.inv(H), (1000,1000))
im4_warped[0:im1.shape[0], 0:im1.shape[1]] = im1
cv.imwrite('Q3.jpg',im4_warped)
cv.namedWindow("Image 1", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 1", im1)
cv.waitKey(0)
cv.namedWindow("Image 4", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 4", im4)
cv.waitKey(0)
cv.namedWindow("Stitched", cv.WINDOW_AUTOSIZE)
cv.imshow("Stitched", im4_warped)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
N = 5
global n
n = 0
p1 = np.empty((N,2))
p2 = np.empty((N,2))
# mouse callback function
def draw_circle(event,x,y,flags,param):
    global n
    p = param[0]
    if event == cv.EVENT_LBUTTONDOWN:
        cv.circle(param[1],(x,y),5,(255,0,0),-1)
        p[n] = (x,y)
        n += 1


im1 = cv.imread('images/assn2/graf/img1.ppm', cv.IMREAD_ANYCOLOR)
im4 = cv.imread('images/assn2/graf/img4.ppm', cv.IMREAD_ANYCOLOR)

im1copy = im1.copy()
im4copy = im4.copy()

cv.namedWindow('Image 1', cv.WINDOW_AUTOSIZE)

param = [p1, im1copy]
cv.setMouseCallback('Image 1',draw_circle, param)

while(1):
    cv.imshow("Image 1", im1copy)
    if n == N:
        break
    if cv.waitKey(20) & 0xFF == 27:
        break

param = [p2, im4copy]
n = 0
cv.namedWindow("Image 4", cv.WINDOW_AUTOSIZE)
cv.setMouseCallback('Image 4',draw_circle, param)

while(1):
    cv.imshow("Image 4", im4copy)
    if n == N:
        break
    if cv.waitKey(20) & 0xFF == 27:
        break
print(p1)
print(p2)

A = []
for i in range(len(p1)):
    pt1 = np.matrix([p1[i].item(0), p1[i].item(1), 1]) #convert to homogeneous
    pt2 = np.matrix([p2[i].item(0), p2[i].item(1), 1]) #convert to homogeneous

    ay = [0, 0, 0, -pt2.item(2) * pt1.item(0), -pt2.item(2) * pt1.item(1), -pt2.item(2) * pt1.item(2),
            pt2.item(1) * pt1.item(0), pt2.item(1) * pt1.item(1), pt2.item(1) * pt1.item(2)]
    ax = [-pt2.item(2) * pt1.item(0), -pt2.item(2) * pt1.item(1), -pt2.item(2) * pt1.item(2), 0, 0, 0,
            pt2.item(0) * pt1.item(0), pt2.item(0) * pt1.item(1), pt2.item(0) * pt1.item(2)]
    A.append(ax)
    A.append(ay)

matrixA = np.matrix(A)

#svd composition to calculate H using least squares
u, s, v = np.linalg.svd(matrixA)
# the last item of v orthogonal matrices gives the answer to H, reshape it into a 3x3 matrix
H = np.reshape(v[8], (3, 3))
H = (1/H.item(8)) * H 
print(H)
im4_warped = cv.warpPerspective(im4, np.linalg.inv(H), (1000,1000))
im4_warped[0:im1.shape[0], 0:im1.shape[1]] = im1
cv.imwrite('Q4.jpg',im4_warped)
cv.namedWindow("Image 1", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 1", im1)
cv.waitKey(0)
cv.namedWindow("Image 4", cv.WINDOW_AUTOSIZE)
cv.imshow("Image 4", im4)
cv.waitKey(0)
cv.namedWindow("Stitched", cv.WINDOW_AUTOSIZE)
cv.imshow("Stitched", im4_warped)
cv.waitKey(0)
cv.destroyAllWindows()

In [1]:
import numpy as np


In [9]:
X =np.array(([3,2,1],[1,2,3]))
print(X.shape)
print(X)

(2, 3)
[[3 2 1]
 [1 2 3]]


In [13]:
X =np.array([3,2,1])
print((X.T).shape)
print(X.T)

(3,)
[3 2 1]


In [14]:
import numpy as np
from numpy import linalg as LA
X=np.array([[0],[1],[2],[3],[4]])
Y=np.array([[3.7183],[4.0196],[6.9012],[8.3961],[4]])
x_mean=np.mean(X)
y_mean=np.mean(Y)
U=np.concatenate((X-x_mean,Y-y_mean),axis=1)
A=np.matmul(U.transpose(),U)
print(A)
eigen_values, eigen_vectors = LA.eig(A)
print(eigen_values)
print(eigen_vectors)

[[10.          4.9399    ]
 [ 4.9399     17.92358789]]
[ 7.62946236 20.29412553]
[[-0.90156679 -0.43263994]
 [ 0.43263994 -0.90156679]]


In [15]:
import numpy as np
Y=np.array([[3.7183], [4.0196], [6.9012], [8.3961],[4.0000]])
X=np.array([[0,1],[1,1],[2,1],[3,1],[4,1]])
a=np.linalg.inv((np.matmul(X.transpose(),X)))
b=np.matmul(X.transpose(),Y)
c=np.matmul(a,b)
print(c)

[[0.49399]
 [4.41906]]
